import { TextContentHeading } from "../../../ui/typography";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextContentHeading,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=2153%3A7834",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      heading: figma.string("Heading"),
      subheading: figma.string("Subheading"),
      hasSubheading: figma.boolean("Has Subheading"),
      align: figma.enum("Align", {
        Start: "Start",
        Center: "Center",
      }),
      // No matching props could be found for these Figma properties:
      // "hasSubheading": figma.boolean('Has Subheading'),
      // "heading": figma.string('Heading'),
      // "subheading": figma.string('Subheading')
    },
    example: (props) => (
      <TextContentHeading
        heading={props.heading}
        subheading={props.subheading}
        hasSubheading={props.hasSubheading}
        align={props.align}
      />
    ),
  }
);
