import { PageProductDetail } from "../../../ui/sections";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  PageProductDetail,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A15147",
  {
    props: {},
    example: () => (
      <PageProductDetail
        title="Text Heading"
        price={50}
        description="Text"
        selectField1Label="Label"
        selectField1Options={[
          { label: "Small", value: "sm" },
          { label: "Medium", value: "md" },
          { label: "Large", value: "lg" },
        ]}
        selectField2Label="Label"
        selectField2Options={[
          { label: "Black", value: "black" },
          { label: "White", value: "white" },
        ]}
      />
    ),
  }
);
