import { PageNewsletter } from "../../../ui/sections/PageNewsletter/PageNewsletter";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  PageNewsletter,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A15133",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: () => (
      <PageNewsletter
        heading="Follow the latest trends"
        subheading="With our daily newsletter"
        onSubmit={async () => {}}
        submitButtonText="Submit"
      />
    ),
  }
);
