import { Avatar, TestimonialCard } from "../../../ui/primitives";
import { CardGridTestimonials } from "../../../ui/sections";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CardGridTestimonials,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A13347",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: () => (
      <CardGridTestimonials
        heading="What Our Users Say"
        subheading="Real feedback from real users"
      >
        <TestimonialCard
          quote="A game-changer for our organization. Highly recommended to anyone in the industry!"
          avatar={<Avatar type="initial" name="Alex Johnson" size="md" />}
          name="Alex Johnson"
          role="VP of Engineering"
        />
        <TestimonialCard
          quote="Seamless integration with our existing tools. The documentation is top-notch."
          avatar={<Avatar type="initial" name="Taylor Brown" size="md" />}
          name="Taylor Brown"
          role="Lead Developer"
        />
        <TestimonialCard
          quote="Worth every penny. The value proposition is clear and delivered upon."
          avatar={<Avatar type="initial" name="Morgan Lee" size="md" />}
          name="Morgan Lee"
          role="Business Analyst"
        />
      </CardGridTestimonials>
    ),
  }
);
