import { ButtonGroup } from "../../ui/primitives/Button/ButtonGroup";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ButtonGroup,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk/Simple-Design-System--Community-?node-id=2072%3A9432",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "buttonStart": figma.boolean('Button Start'),
      // "buttonEnd": figma.boolean('Button End'),
      align: figma.enum("Align", {
        Justify: "justify",
        Start: "start",
        End: "end",
        Center: "center",
        Stack: "stack",
      }),
    },
    example: (props) => <ButtonGroup align={props.align}>Buttons</ButtonGroup>,
  }
);
