import { Button } from "../../ui/primitives/Button/Button";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk/Simple-Design-System--Community-?node-id=4185%3A3778",
  {
    props: {
      variant: figma.enum("Variant", {
        Primary: "primary",
        Neutral: "neutral",
        Subtle: "subtle",
      }),
      size: figma.enum("Size", {
        Small: "sm",
      }),
      icon: figma.instance("Icon End"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      label: figma.string("Label"),
      iconEnd: figma.instance("Icon End"),
      hasIconEnd: figma.boolean("Has Icon End"),
      hasIconStart: figma.boolean("Has Icon Start"),
      iconStart: figma.instance("Icon Start"),
    },
    example: (props) => (
      <Button
        variant={props.variant}
        size={props.size}
        disabled={props.disabled}
        iconStart={props.iconStart}
        iconEnd={props.iconEnd}
      >
        {props.label}
      </Button>
    ),
  }
);
