import { TextPrice } from "../../../ui/typography";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextPrice,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=1443%3A10386",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      price: figma.string("Price"),
      currency: figma.string("Currency"),
      label: figma.string("Label"),
      hasLabel: figma.boolean("Has Label"),
      size: figma.enum("Size", {
        Large: "Large",
        Small: "Small",
      }),
      // No matching props could be found for these Figma properties:
      // "price": figma.string('Price'),
      // "label": figma.string('Label'),
      // "currency": figma.string('Currency'),
      // "hasLabel": figma.boolean('Has Label')
    },
    example: (props) => (
      <TextPrice
        price={props.price}
        currency={props.currency}
        label={props.label}
        hasLabel={props.hasLabel}
        size={props.size}
      />
    ),
  }
);
