import { CheckboxField, CheckboxGroup } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CheckboxGroup,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=9762%3A1426",
  {
    props: {},
    example: () => (
      <CheckboxGroup>
        <CheckboxField label="Label" description="Description" />
        <CheckboxField label="Label" description="Description" />
        <CheckboxField label="Label" description="Description" />
      </CheckboxGroup>
    ),
  }
);
