import { Avatar, TestimonialCard } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  TestimonialCard,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=7717%3A3946",
  {
    props: {},
    example: () => (
      <TestimonialCard
        quote="This product has transformed our workflow completely. The team's productivity increased by 40% within the first month. Highly recommended!"
        avatar={
          <Avatar
            type="image"
            src="https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop"
            alt="Sarah Johnson"
            size="md"
          />
        }
        name="Sarah Johnson"
        role="CEO at TechCorp"
      />
    ),
  }
);
