import { TextListItem, TextList } from "../../../ui/typography";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextList,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=480%3A6149",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      hasTitle: figma.boolean("Has Title"),
      density: figma.enum("Density", {
        Default: "Default",
        Tight: "Tight",
      }),
      // No matching props could be found for these Figma properties:
      // "hasTitle": figma.boolean('Has Title')
    },
    example: (props) => (
      <TextList hasTitle={props.hasTitle} density={props.density}>
        <TextListItem text="First list item" />
        <TextListItem text="Second list item" />
        <TextListItem text="Third list item" />
        <TextListItem text="Fourth list item" />
      </TextList>
    ),
  }
);
