import { CardGridImage } from "../../../ui/sections";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CardGridImage,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A14431",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: () => (
      <CardGridImage
        heading="Our Services"
        subheading="Discover what we can do for you"
        cards={[
          {
            image:
              "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
            alt: "Design services",
            title: "Design",
            description:
              "Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.",
          },
          {
            image:
              "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
            alt: "Development services",
            title: "Development",
            description:
              "Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.",
          },
          {
            image:
              "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop",
            alt: "Marketing services",
            title: "Marketing",
            description:
              "Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.",
          },
        ]}
      />
    ),
  }
);
