import { CardGridContentList } from "../../../ui/sections/CardGridContentList/CardGridContentList";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CardGridContentList,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A13407",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: () => (
      <CardGridContentList
        heading="Featured Profiles"
        subheading="Discover talented individuals from our community"
        cards={[
          {
            image: "/avatar1.svg",
            alt: "User avatar 1",
            title: "Professional Profile",
            body: "Body text for whatever you'd like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.",
            buttonText: "View Profile",
          },
          {
            image: "/avatar2.svg",
            alt: "User avatar 2",
            title: "Team Member Spotlight",
            body: "Highlighting the achievements and contributions of our dedicated team members who make everything possible.",
            buttonText: "Learn More",
          },
          {
            image: "/avatar3.svg",
            alt: "User avatar 3",
            title: "Success Story",
            body: "Read about how our platform has helped users achieve their goals and transform their workflows.",
            buttonText: "Read Story",
          },
        ]}
      />
    ),
  }
);
