import figma from "@figma/code-connect";
import { TagToggleGroup } from "../../../ui/primitives";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  TagToggleGroup,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=157%3A10352",
  {
    props: {},
    example: () => (
      <TagToggleGroup
        items={[
          { id: "react", label: "React" },
          { id: "vue", label: "Vue" },
          { id: "angular", label: "Angular" },
        ]}
        selectedIds={["react"]}
        onToggle={() => {}}
      />
    ),
  }
);
