import figma from "@figma/code-connect";
import { PricingCard } from "../../../ui/primitives";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  PricingCard,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=1444%3A11846",
  {
    props: {},
    example: () => (
      <PricingCard
        title="Professional"
        price="99"
        currency="$"
        period="/ mo"
        features={[
          "Unlimited projects",
          "Advanced analytics",
          "Priority support",
          "Team collaboration",
        ]}
        buttonLabel="Start Free Trial"
        onButtonClick={() => {}}
        isBrand={true}
      />
    ),
  }
);
