import figma from "@figma/code-connect";
import { PricingCard } from "../../../ui/primitives";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  PricingCard,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=1444%3A11846",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      variant: figma.enum("Variant", {
        Stroke: "Stroke",
        Brand: "Brand",
      }),
      // No matching props could be found for these Figma properties:
      // "device": figma.enum('Device', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: (props) => (
      <PricingCard
        variant={props.variant}
        title="Starter"
        price="29"
        currency="$"
        priceLabel="/ mo"
        list={[
          "10 projects",
          "Basic analytics",
          "Email support",
          "Community access",
        ]}
        buttonText="Start Free Trial"
        onButtonClick={() => {}}
      />
    ),
  }
);
