import { Button, ButtonGroup } from "../../../ui/primitives";
import { HeroImage } from "../../../ui/sections";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  HeroImage,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A15970",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: () => (
      <HeroImage
        title="Title"
        subtitle="Subtitle"
        backgroundImage="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1600&auto=format&fit=crop&ixlib=rb-4.0.3&s=abc"
      >
        <ButtonGroup align="center">
          <Button variant="neutral">Button</Button>
          <Button variant="primary">Button</Button>
        </ButtonGroup>
      </HeroImage>
    ),
  }
);
