import { TextTitleHero } from "../../../ui/typography/TextTitleHero";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextTitleHero,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=2087%3A8491",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      text: figma.string("Text"),
      // No matching props could be found for these Figma properties:
      // "text": figma.string('Text')
    },
    example: (props) => <TextTitleHero text={props.text} />,
  }
);
