import figma from "@figma/code-connect";
import { ReviewCard } from "../../../ui/primitives";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  ReviewCard,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=2236%3A16106",
  {
    props: {},
    example: () => (
      <ReviewCard
        rating={5}
        reviewTitle="Excellent Product!"
        reviewBody="This product exceeded all my expectations. The quality is outstanding and the customer service was fantastic. Highly recommended for anyone looking for reliability and performance."
        reviewerName="Sarah Johnson"
        reviewDate={new Date()}
        avatarSrc="/avatar5.svg"
      />
    ),
  }
);
