import { CardGridReviews } from "../../../ui/sections";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CardGridReviews,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A15213",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: () => (
      <CardGridReviews
        heading="Latest reviews"
        reviews={[
          {
            id: "1",
            title: "Review title",
            body: "Review body",
            rating: 5,
            reviewerName: "Reviewer name",
            reviewDate: new Date(2024, 11, 15),
            avatarSrc: "/avatars/john.jpg",
            avatarAlt: "Reviewer avatar",
          },
          {
            id: "2",
            title: "Review title",
            body: "Review body",
            rating: 5,
            reviewerName: "Reviewer name",
            reviewDate: new Date(2024, 11, 15),
            avatarSrc: "/avatars/john.jpg",
            avatarAlt: "Reviewer avatar",
          },
          {
            id: "3",
            title: "Review title",
            body: "Review body",
            rating: 5,
            reviewerName: "Reviewer name",
            reviewDate: new Date(2024, 11, 15),
            avatarSrc: "/avatars/john.jpg",
            avatarAlt: "Reviewer avatar",
          },
        ]}
      />
    ),
  }
);
