import AvatarBlock from "../../../ui/primitives/Avatar/AvatarBlock"
import Avatar from "../../../ui/primitives/Avatar/Avatar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  AvatarBlock,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=2010%3A15581",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      title: figma.string("Title"),
      description: figma.string("Description"),
      // No matching props could be found for these Figma properties:
      // "title": figma.string('Title'),
      // "description": figma.string('Description')
    },
    example: (props) => (
      <AvatarBlock
        avatar={<Avatar type="image" src="/avatar.jpg" alt="User" />}
        title={props.title}
        description={props.description}
      />
    ),
  },
)
