import { AvatarGroup, Avatar } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  AvatarGroup,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=56%3A15608",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      spacing: figma.enum("Spacing", {
        Spaced: "spaced",
        Overlap: "overlap",
      }),
      showOverflow: figma.boolean("Show Overflow"),
      // No matching props could be found for these Figma properties:
      // "showOverflow": figma.boolean('Show Overflow'),
      // "number": figma.string('Number')
    },
    example: (props) => (
      <AvatarGroup spacing={props.spacing} showOverflow={props.showOverflow}>
        <Avatar type="image" src="/avatar1.jpg" alt="User 1" />
        <Avatar type="initial" src="/avatar2.jpg" alt="User 2" />
        <Avatar type="image" src="/avatar3.jpg" alt="User 3" />
      </AvatarGroup>
    ),
  }
);
