import { Avatar } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Avatar,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=9762%3A1103",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      alt: figma.string("Initials"),
      size: figma.enum("Size", {
        Small: "sm",
        Medium: "md",
        Large: "lg",
      }),
      shape: figma.enum("Shape", {
        Circle: "circle",
        Square: "square",
      }),
      // No matching props could be found for these Figma properties:
      // "initials": figma.string('Initials'),
      type: figma.enum("Type", {
        Initial: "initial",
        Image: "image",
      }),
    },
    example: (props) => (
      <Avatar
        type={props.type}
        name={props.alt}
        src="/avatar.jpg"
        alt={props.alt}
        size={props.size}
        shape={props.shape}
      />
    ),
  }
);
