import { NavigationPillList } from "../../../ui/primitives/Navigation/NavigationPillList";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  NavigationPillList,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=2194%3A14984",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "link6": figma.boolean('Link 6'),
      // "link2": figma.boolean('Link 2'),
      // "link5": figma.boolean('Link 5'),
      // "link4": figma.boolean('Link 4'),
      // "link3": figma.boolean('Link 3'),
      // "link1": figma.boolean('Link 1'),
      // "link7": figma.boolean('Link 7'),
      direction: figma.enum("Direction", {
        Row: "row",
        Column: "column",
      }),
    },
    example: () => (
      <NavigationPillList
        items={[
          { id: "1", label: "Overview" },
          { id: "2", label: "Analytics" },
          { id: "3", label: "Reports" },
        ]}
        direction="row"
      />
    ),
  }
);
