import { NavigationList } from "../../../ui/primitives";
import figma from "@figma/code-connect";
import {
  IconActivity,
  IconAlertCircle,
  IconArchive,
  IconCheckCircle,
} from "../../../ui/icons";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  NavigationList,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=524%3A503",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      direction: figma.enum("Direction", {
        Column: "column",
        Row: "row",
      }),
      // No matching props could be found for these Figma properties:
      // "link2": figma.boolean('Link 2'),
      // "link5": figma.boolean('Link 5'),
      // "link4": figma.boolean('Link 4'),
      // "link3": figma.boolean('Link 3'),
      // "link1": figma.boolean('Link 1')
    },
    example: (props) => (
      <NavigationList
        items={[
          {
            id: "home",
            label: "Home",
            icon: <IconActivity size="24" />,
            itemDirection: "column",
          },
          {
            id: "notifications",
            label: "Notifications",
            icon: <IconAlertCircle size="24" />,
          },
          {
            id: "archive",
            label: "Archive",
            icon: <IconArchive size="24" />,
          },
          {
            id: "completed",
            label: "Completed",
            icon: <IconCheckCircle size="24" />,
          },
        ]}
        direction={props.direction}
      />
    ),
  }
);
