import { IconInfo } from "../../../ui/icons";
import { CardGridIcon } from "../../../ui/sections";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CardGridIcon,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A13221",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: () => (
      <CardGridIcon
        heading="Heading"
        subheading="Subheading"
        cards={[
          {
            icon: <IconInfo size="32" />,
            title: "Title",
            description:
              "Body text for whatever you’d like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.",
          },
          {
            icon: <IconInfo size="32" />,
            title: "Title",
            description:
              "Body text for whatever you’d like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.",
          },
          {
            icon: <IconInfo size="32" />,
            title: "Title",
            description:
              "Body text for whatever you’d like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.",
          },
          {
            icon: <IconInfo size="32" />,
            title: "Title",
            description:
              "Body text for whatever you’d like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.",
          },
          {
            icon: <IconInfo size="32" />,
            title: "Title",
            description:
              "Body text for whatever you’d like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.",
          },
          {
            icon: <IconInfo size="32" />,
            title: "Title",
            description:
              "Body text for whatever you’d like to say. Add main takeaway points, quotes, anecdotes, or even a very very short story.",
          },
        ]}
      />
    ),
  }
);
