import { HeroActions } from "../../../ui/sections";
import figma from "@figma/code-connect";
import { Button } from "../../../ui/primitives";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  HeroActions,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A15901",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: () => (
      <HeroActions
        title="Build amazing experiences with our platform"
        subtitle="Start creating beautiful, responsive applications in minutes with our comprehensive design system"
        buttons={
          <>
            <Button variant="primary" size="lg">
              Get Started
            </Button>
            <Button variant="neutral" size="lg">
              Learn More
            </Button>
          </>
        }
      />
    ),
  }
);
