import { IconActivity, IconAirplay, IconAlertCircle } from "../../../ui/icons";
import { Avatar, Button, Tabs } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Tabs,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=3729%3A13362",
  {
    props: {},
    example: () => (
      <Tabs
        items={[
          {
            id: "icons",
            label: "Icons",
            content: (
              <section>
                <h2 className="text-2xl font-bold mb-4">Icons</h2>
                <div className="flex gap-1.5 justify-between items-center">
                  <IconActivity size="40" />
                  <IconAirplay size="40" />
                  <IconAlertCircle size="40" />
                </div>
              </section>
            ),
          },
          {
            id: "buttons",
            label: "Buttons",
            content: (
              <section>
                <h2 className="text-2xl font-bold mb-4">Button Variants</h2>
                <div className="flex flex-wrap gap-4 items-center">
                  <Button variant="primary">Primary Button</Button>
                  <Button variant="neutral">Neutral Button</Button>
                  <Button variant="subtle">Subtle Button</Button>
                </div>
              </section>
            ),
          },
          {
            id: "avatars",
            label: "Avatars",
            content: (
              <section>
                <h2 className="text-2xl font-bold mb-4">Image Avatars</h2>
                <div className="flex flex-wrap gap-4 items-center">
                  <Avatar
                    type="image"
                    src="/avatar1.svg"
                    alt="User 1"
                    size="sm"
                    shape="circle"
                  />
                  <Avatar
                    type="image"
                    src="/avatar2.svg"
                    alt="User 2"
                    size="md"
                    shape="circle"
                  />
                  <Avatar
                    type="image"
                    src="/avatar3.svg"
                    alt="User 3"
                    size="lg"
                    shape="circle"
                  />
                </div>
              </section>
            ),
          },
        ]}
        defaultActiveTab="icons"
      />
    ),
  }
);
