import { HeaderAuth } from "../../../ui/sections/HeaderAuth/HeaderAuth";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  HeaderAuth,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=18%3A9389",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "state": figma.enum('State', {
      //   "Logged In": "logged-in",
      //   "Logged Out": "logged-out",
      //   "Logged In - Hover": "logged-in---hover"
      // })
    },
    example: () => (
      <HeaderAuth
        isLoggedIn={true}
        avatarSrc="/images/user-avatar.jpg"
        avatarAlt="John Doe"
        userName="John Doe"
        onAvatarClick={() => {}}
      />
    ),
  }
);
