import figma from "@figma/code-connect";
import { PageAccordion } from "../../../ui/sections";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  PageAccordion,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A13173",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: () => (
      <PageAccordion
        heading="Frequently Asked Questions"
        subheading="Find answers to common questions about our service"
        items={[
          {
            id: 1,
            title: "What is your return policy?",
            content:
              "We offer a 30-day money-back guarantee on all purchases. If you're not satisfied with your product, you can return it for a full refund within 30 days of purchase.",
          },
          {
            id: 2,
            title: "How long does shipping take?",
            content:
              "Standard shipping typically takes 5-7 business days. Express shipping options are available at checkout for faster delivery.",
          },
          {
            id: 3,
            title: "Do you ship internationally?",
            content:
              "Yes, we ship to most countries worldwide. International shipping rates and delivery times vary by destination.",
          },
          {
            id: 4,
            title: "How can I track my order?",
            content:
              "Once your order ships, you'll receive a tracking number via email. You can use this number to track your package on our website or the carrier's site.",
          },
          {
            id: 5,
            title: "What payment methods do you accept?",
            content:
              "We accept all major credit cards (Visa, MasterCard, American Express), PayPal, Apple Pay, and Google Pay for your convenience.",
          },
        ]}
        allowMultiple={false}
      />
    ),
  }
);
