import { PanelImageDouble } from "../../../ui/sections";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  PanelImageDouble,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A13470",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: () => (
      <PanelImageDouble
        leftImageSrc="https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&h=600&fit=crop"
        rightImageSrc="https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&h=600&fit=crop"
      />
    ),
  }
);
