import { ButtonDanger } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ButtonDanger,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk/Simple-Design-System--Community-?node-id=185%3A852",
  {
    props: {
      // No matching props could be found for these Figma properties:
      label: figma.string("Label"),
      iconEnd: figma.instance("Icon End"),
      // hasIconEnd: figma.boolean("Has Icon End"),
      // hasIconStart: figma.boolean("Has Icon Start"),
      iconStart: figma.instance("Icon Start"),
      variant: figma.enum("Variant", {
        Primary: "primary",
        Subtle: "subtle",
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      size: figma.enum("Size", {
        Medium: "md",
        Small: "sm",
      }),
    },
    example: (props) => (
      <ButtonDanger
        variant={props.variant}
        disabled={props.disabled}
        size={props.size}
        iconStart={props.iconStart}
        iconEnd={props.iconEnd}
      >
        {props.label}
      </ButtonDanger>
    ),
  }
);
