import figma from "@figma/code-connect";
import { Button, Card } from "../../../ui/primitives";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Card,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=2142%3A11380",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      heading: figma.string("Heading"),
      body: figma.string("Body"),
      icon: figma.instance("Icon"),
      assetType: figma.enum("Asset Type", {
        Icon: "Icon",
        Image: "Image",
      }),
      variant: figma.enum("Variant", {
        Stroke: "Stroke",
        Default: "Default",
      }),
      direction: figma.enum("Direction", {
        Horizontal: "Horizontal",
        Vertical: "Vertical",
      }),
      // No matching props could be found for these Figma properties:
      // "asset": figma.boolean('Asset'),
      // "button": figma.boolean('Button'),
      // "heading": figma.string('Heading'),
      // "body": figma.string('Body'),
      // "icon": figma.instance('Icon')
    },
    example: (props) => (
      <Card
        assetType={props.assetType}
        image="/avatar5.svg"
        alt="User avatar"
        heading={props.heading}
        body={props.body}
        variant={props.variant}
        direction={props.direction}
      >
        <Button variant="neutral">View Profile</Button>
      </Card>
    ),
  }
);
