import { InputField } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  InputField,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=2136%3A2263",
  {
    props: {
      label: figma.string("Label"),
      hasError: figma.boolean("Has Error"),
      state: figma.enum("State", {
        Default: undefined,
        Error: undefined,
        Disabled: true,
      }),
      value: figma.string("Value"),
      error: figma.string("Error"),
      description: figma.string("Description"),
    },
    example: (props) => (
      <InputField
        label={props.label}
        hasError={props.hasError}
        disabled={props.state}
        value={props.value}
        description={props.description}
      />
    ),
  }
);
