import { RadioField } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  RadioField,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=9762%3A1412",
  {
    props: {
      description: figma.string("Description"),
      label: figma.string("Label"),
      state: figma.enum("State", {
        Default: false,
        Disabled: true,
      }),
      // valueType: figma.enum("Value Type", {
      //   Checked: "Checked",
      //   Unchecked: "Unchecked",
      // }),
    },
    example: (props) => (
      <RadioField
        label={props.label}
        description={props.description}
        disabled={props.state}
        onChange={() => {}}
      />
    ),
  }
);
