import { RadioField, RadioGroup } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  RadioGroup,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=624%3A23642",
  {
    props: {},
    example: () => (
      <RadioGroup name="options">
        <RadioField label="Label" description="Description" value="option1" />
        <RadioField label="Label" description="Description" value="option2" />
        <RadioField label="Label" description="Description" value="option3" />
      </RadioGroup>
    ),
  }
);
