import { SearchField } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SearchField,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=2236%3A14989",
  {
    props: {
      state: figma.enum("State", {
        Default: false,
        Disabled: true,
      }),
      value: figma.string("Value"),
    },
    example: (props) => (
      <SearchField disabled={props.state} value={props.value} />
    ),
  }
);
