import { SliderField } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  SliderField,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=589%3A17676",
  {
    props: {
      label: figma.string("Label"),
      description: figma.string("Description"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
    },
    example: (props) => (
      <SliderField
        label={props.label}
        description={props.description}
        disabled={props.disabled}
      />
    ),
  }
);
