import { TextareaField } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextareaField,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=9762%3A3088",
  {
    props: {
      label: figma.string("Label"),
      hasError: figma.enum("State", {
        Error: true,
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      value: figma.string("Value"),
      errorMessage: figma.string("Error"),
      description: figma.string("Description"),
    },
    example: (props) => (
      <TextareaField
        label={props.label}
        hasError={props.hasError}
        disabled={props.disabled}
        value={props.value}
        description={props.description}
        errorMessage={props.errorMessage}
      />
    ),
  }
);
