import { TextContentTitle } from "../../../ui/typography";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextContentTitle,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=2153%3A7838",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      align: figma.enum("Align", {
        Start: "start",
        Center: "center",
      }),
      hasSubtitle: figma.boolean("Has Subtitle"),
      title: figma.string("Title"),
      subtitle: figma.string("Subtitle"),
      // No matching props could be found for these Figma properties:
      // "subtitle": figma.string('Subtitle'),
      // "hasSubtitle": figma.boolean('Has Subtitle'),
      // "title": figma.string('Title')
    },
    example: (props) => (
      <TextContentTitle
        align={props.align}
        hasSubtitle={props.hasSubtitle}
        title={props.title}
        subtitle={props.subtitle}
      />
    ),
  }
);
