import figma from "@figma/code-connect";
import { ProductInfoCard } from "../../../ui/primitives";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ProductInfoCard,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=7753%3A4465",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      showDescription: figma.boolean("Show Description"),
      // No matching props could be found for these Figma properties:
      // "showDescription": figma.boolean('Show Description')
    },
    example: (props) => (
      <ProductInfoCard
        productName="Wireless Mouse"
        price="$49.99"
        description="Ergonomic design with precision tracking"
        imageUrl="/product.svg"
        imageAlt="Wireless Mouse"
        showDescription={props.showDescription}
      />
    ),
  }
);
