import figma from "@figma/code-connect";
import { CardGridPricing } from "../../../ui/sections";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  CardGridPricing,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A14983",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: () => (
      <CardGridPricing
        activePeriod="yearly"
        onPeriodChange={() => {}}
        cards={[
          {
            title: "Starter",
            price: "29",
            features: ["10 projects", "Basic analytics", "Email support"],
            buttonLabel: "Start Free Trial",
          },
          {
            title: "Professional",
            price: "99",
            features: [
              "Unlimited projects",
              "Advanced analytics",
              "Priority support",
            ],
            buttonLabel: "Start Free Trial",
          },
          {
            title: "Enterprise",
            price: "299",
            features: [
              "Unlimited everything",
              "Custom analytics",
              "24/7 support",
            ],
            buttonLabel: "Contact Sales",
          },
        ]}
      />
    ),
  }
);
