import { TextLinkList, TextLinkListItem } from "../../../ui/typography";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextLinkList,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=322%3A9321",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      hasTitle: figma.boolean("Has Title"),
      density: figma.enum("Density", {
        Default: "Default",
        Tight: "Tight",
      }),
      // No matching props could be found for these Figma properties:
      // "hasTitle": figma.boolean('Has Title')
    },
    example: (props) => (
      <TextLinkList
        titleText="Text Strong"
        hasTitle={props.hasTitle}
        density={props.density}
      >
        <TextLinkListItem text="Home" />
        <TextLinkListItem text="About" />
        <TextLinkListItem text="Services" />
        <TextLinkListItem text="Contact" />
      </TextLinkList>
    ),
  }
);
