import { IconButton } from "../../../ui/primitives";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  IconButton,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk/Simple-Design-System--Community-?node-id=11%3A11508",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      icon: figma.instance("Icon"),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      // No matching props could be found for these Figma properties:
      // "icon": figma.instance('Icon'),
      variant: figma.enum("Variant", {
        Primary: "primary",
        Neutral: "neutral",
        Subtle: "subtle",
      }),
      size: figma.enum("Size", {
        Medium: "md",
        Small: "sm",
      }),
    },
    example: (props) => (
      <IconButton
        variant={props.variant}
        size={props.size}
        icon={props.icon}
        disabled={props.disabled}
      />
    ),
  }
);
