import figma from "@figma/code-connect";
import { StatsCard } from "../../../ui/primitives";
import { IconClock } from "../../../ui/icons";

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  StatsCard,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=2236%3A15082",
  {
    props: {
      // Icon mapping - using IconClock as example since Figma instances
      // don't directly map to specific Icon components
      icon: figma.instance("Icon"),
    },
    example: () => (
      <StatsCard icon={<IconClock />} value="567" label="Active Users" />
    ),
  }
);
