import { PageProductResults } from "../../../ui/sections";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  PageProductResults,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=348%3A13517",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // })
    },
    example: () => (
      <PageProductResults
        products={[
          {
            id: "1",
            name: "Wireless Mouse",
            price: "$49.99",
            description: "Ergonomic design",
          },
          {
            id: "2",
            name: "Keyboard",
            price: "$79.99",
            description: "Mechanical switches",
          },
        ]}
        categoryItems={[
          { id: "tech", label: "Tech" },
          { id: "accessories", label: "Accessories" },
        ]}
        labelOptions={[
          {
            id: "new-arrival",
            label: "New Arrival",
            description: "Recently added products",
          },
          {
            id: "best-seller",
            label: "Best Seller",
            description: "Most popular items",
          },
          {
            id: "on-sale",
            label: "On Sale",
            description: "Discounted products",
          },
        ]}
        colorOptions={[
          { id: "black", label: "Black" },
          { id: "white", label: "White" },
          { id: "silver", label: "Silver" },
        ]}
        sizeOptions={[
          { id: "small", label: "Small" },
          { id: "medium", label: "Medium" },
          { id: "large", label: "Large" },
        ]}
      />
    ),
  }
);
