import { IconFigma } from "../../../ui/icons";
import Header from "../../../ui/sections/Header/Header";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  Header,
  "https://www.figma.com/design/2FK25kD8bhdmjk3iTu97Vk?node-id=2287%3A22651",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "platform": figma.enum('Platform', {
      //   "Desktop": "desktop",
      //   "Mobile": "mobile"
      // }),
      // "state": figma.enum('State', {
      //   "Open": "open",
      //   "Default": "default"
      // })
    },
    example: () => (
      <Header
        logoIcon={<IconFigma size="32" />}
        navigationItems={[
          { id: "products", label: "Products", href: "/products" },
          { id: "solutions", label: "Solutions", href: "/solutions" },
          { id: "community", label: "Community", href: "/community" },
          { id: "resources", label: "Resources", href: "/resources" },
          { id: "pricing", label: "Pricing", href: "/pricing" },
          { id: "contact", label: "Contact", href: "/contact" },
        ]}
        isLoggedIn={true}
      />
    ),
  }
);
